APP:
    dname: emulator-5554
    apk :  com.netease.cloudmusic
webUrl:
    testurl: http://shopxo.hctestedu.com/
    devurl:  https://www.baidu.com/
    prourl:  https://www.baidu.com/

Api:
    testurl: http://127.0.0.1:5000/
    devurl:  https://www.baidu.com/
    prourl:  https://www.baidu.com/

RunApi:   #表示运行用例的          1
RunApis:  #表示按顺序运行部分用例  [1,3,5]

Browser:
    name: chrome  #火狐 ，ie
    env:  localhost  #阿里云  ，无头，docker

database:
    username: root
    password: root
    dbname: test
    serve: localhost
    port : 3307
